//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"


// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;


MainFrameBaseClass::MainFrameBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer1 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer1);
    
    m_mainPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer1->Add(m_mainPanel, 1, wxEXPAND, 5);
    
    wxBoxSizer* boxSizer13 = new wxBoxSizer(wxHORIZONTAL);
    m_mainPanel->SetSizer(boxSizer13);
    
    wxBoxSizer* boxSizer65 = new wxBoxSizer(wxVERTICAL);
    
    boxSizer13->Add(boxSizer65, 1, wxALL|wxEXPAND, 5);
    
    wxBoxSizer* boxSizer67 = new wxBoxSizer(wxHORIZONTAL);
    
    boxSizer65->Add(boxSizer67, 9, wxALL|wxEXPAND, 5);
    
    m_scrollWin = new MyImageWin(m_mainPanel, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxHSCROLL|wxVSCROLL);
    m_scrollWin->SetScrollRate(20, 20);
    
    boxSizer67->Add(m_scrollWin, 3, wxEXPAND, 5);
    
    wxBoxSizer* boxSizer69 = new wxBoxSizer(wxVERTICAL);
    
    boxSizer67->Add(boxSizer69, 2, wxALL|wxEXPAND, 5);
    
    wxArrayString m_radioBoxPointsArr;
    m_radioBoxPointsArr.Add(_("0VX_PARLLEL_LINE1_P2"));
    m_radioBoxPointsArr.Add(_("1VX_PARLLEL_LINE1_P1"));
    m_radioBoxPointsArr.Add(_("2VX_PARLLEL_LINE2_P1"));
    m_radioBoxPointsArr.Add(_("3VX_PARLLEL_LINE2_P2"));
    m_radioBoxPointsArr.Add(_("4VY_PARLLEL_LINE1_P1"));
    m_radioBoxPointsArr.Add(_("5VY_PARLLEL_LINE1_P2"));
    m_radioBoxPointsArr.Add(_("6VY_PARLLEL_LINE2_P1"));
    m_radioBoxPointsArr.Add(_("7VY_PARLLEL_LINE2_P2"));
    m_radioBoxPointsArr.Add(_("8VZ_PARLLEL_LINE1_P1"));
    m_radioBoxPointsArr.Add(_("9VZ_PARLLEL_LINE1_P2"));
    m_radioBoxPointsArr.Add(_("10VZ_PARLLEL_LINE2_P1"));
    m_radioBoxPointsArr.Add(_("11VZ_PARLLEL_LINE2_P2"));
    m_radioBoxPointsArr.Add(_("12OBJECT_T"));
    m_radioBoxPointsArr.Add(_("13OBJECT_B"));
    m_radioBoxPointsArr.Add(_("14TARGET_T"));
    m_radioBoxPointsArr.Add(_("15TARGET_B"));
    m_radioBoxPoints = new wxRadioBox(m_mainPanel, wxID_ANY, _("Pin Points"), wxDefaultPosition, wxSize(-1,-1), m_radioBoxPointsArr, 1, wxRA_SPECIFY_COLS);
    m_radioBoxPoints->SetSelection(0);
    
    boxSizer69->Add(m_radioBoxPoints, 0, wxEXPAND, 5);
    
    wxFlexGridSizer* flexGridSizer71 = new wxFlexGridSizer(0, 2, 0, 0);
    flexGridSizer71->SetFlexibleDirection( wxBOTH );
    flexGridSizer71->SetNonFlexibleGrowMode( wxFLEX_GROWMODE_SPECIFIED );
    
    boxSizer69->Add(flexGridSizer71, 0, wxALL|wxEXPAND, 5);
    
    m_staticText87 = new wxStaticText(m_mainPanel, wxID_ANY, _("Vanish P1"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticText87, 0, wxALL, 5);
    
    m_staticTextVanishP1 = new wxStaticText(m_mainPanel, wxID_ANY, _("??"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticTextVanishP1, 0, wxALL, 5);
    
    m_staticText91 = new wxStaticText(m_mainPanel, wxID_ANY, _("Vanish P2"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticText91, 0, wxALL, 5);
    
    m_staticTextVanishP2 = new wxStaticText(m_mainPanel, wxID_ANY, _("??"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticTextVanishP2, 0, wxALL, 5);
    
    m_staticText95 = new wxStaticText(m_mainPanel, wxID_ANY, _("Object T, B"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticText95, 0, wxALL, 5);
    
    m_staticTextObjectTB = new wxStaticText(m_mainPanel, wxID_ANY, _("??"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticTextObjectTB, 0, wxALL, 5);
    
    m_staticText99 = new wxStaticText(m_mainPanel, wxID_ANY, _("TargetOnObj T,B"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticText99, 0, wxALL, 5);
    
    m_staticTextTargetTB = new wxStaticText(m_mainPanel, wxID_ANY, _("??"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticTextTargetTB, 0, wxALL, 5);
    
    m_staticText73 = new wxStaticText(m_mainPanel, wxID_ANY, _("Object Height"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticText73, 0, wxALL, 5);
    
    m_textCtrlOBJh = new wxTextCtrl(m_mainPanel, wxID_ANY, wxT("0"), wxDefaultPosition, wxSize(-1,-1), 0);
    #if wxVERSION_NUMBER >= 3000
    m_textCtrlOBJh->SetHint(wxT(""));
    #endif
    
    flexGridSizer71->Add(m_textCtrlOBJh, 0, wxALL, 5);
    
    m_staticText77 = new wxStaticText(m_mainPanel, wxID_ANY, _("Answer"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticText77, 0, wxALL, 5);
    
    m_staticTextAnswer = new wxStaticText(m_mainPanel, wxID_ANY, _("??"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    flexGridSizer71->Add(m_staticTextAnswer, 0, wxALL, 5);
    
    m_richTextCtrl = new wxRichTextCtrl(m_mainPanel, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), wxTE_MULTILINE|wxTE_PROCESS_TAB|wxTE_PROCESS_ENTER|wxWANTS_CHARS);
    
    boxSizer65->Add(m_richTextCtrl, 3, wxALL|wxEXPAND, 5);
    
    m_menuBar = new wxMenuBar(0);
    this->SetMenuBar(m_menuBar);
    
    m_name6 = new wxMenu();
    m_menuBar->Append(m_name6, _("File"));
    
    m_menuItem81 = new wxMenuItem(m_name6, wxID_OPEN_FILE, _("Open File\tCtrl+O"), wxT(""), wxITEM_NORMAL);
    m_name6->Append(m_menuItem81);
    
    m_menuItem7 = new wxMenuItem(m_name6, wxID_EXIT, _("Exit\tAlt-X"), _("Quit"), wxITEM_NORMAL);
    m_name6->Append(m_menuItem7);
    
    m_name8 = new wxMenu();
    m_menuBar->Append(m_name8, _("Help"));
    
    m_menuItem9 = new wxMenuItem(m_name8, wxID_ABOUT, _("About..."), wxT(""), wxITEM_NORMAL);
    m_name8->Append(m_menuItem9);
    
    m_menuItem103 = new wxMenuItem(m_name8, wxID_ANY, _("Next Point\tTab"), wxT(""), wxITEM_NORMAL);
    m_name8->Append(m_menuItem103);
    
    m_menuItem107 = new wxMenuItem(m_name8, wxID_CLEAR_ALL, _("Clear All"), wxT(""), wxITEM_NORMAL);
    m_name8->Append(m_menuItem107);
    
    m_menu21 = new wxMenu();
    m_menuBar->Append(m_menu21, _("Video"));
    
    m_menuItemCam = new wxMenuItem(m_menu21, wxID_ANY, _("Camera Start"), wxT(""), wxITEM_NORMAL);
    m_menu21->Append(m_menuItemCam);
    
    m_menuItemFile = new wxMenuItem(m_menu21, wxID_ANY, _("Open File"), wxT(""), wxITEM_NORMAL);
    m_menu21->Append(m_menuItemFile);
    
    m_mainToolbar = this->CreateToolBar(wxTB_FLAT, wxID_ANY);
    m_mainToolbar->SetToolBitmapSize(wxSize(16,16));
    
    m_mainToolbar->AddTool(wxID_OPEN_FILE, _("Tool Label"), wxArtProvider::GetBitmap(wxART_FILE_OPEN, wxART_TOOLBAR, wxSize(32, 32)), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_mainToolbar->AddTool(wxID_CLEAR_ALL, _("Tool Label"), wxArtProvider::GetBitmap(wxART_CLOSE, wxART_TOOLBAR, wxDefaultSize), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    m_mainToolbar->Realize();
    
    m_statusBar = new wxStatusBar(this, wxID_ANY, wxSTB_DEFAULT_STYLE);
    m_statusBar->SetFieldsCount(1);
    this->SetStatusBar(m_statusBar);
    
    SetName(wxT("MainFrameBaseClass"));
    SetSizeHints(800,800);
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    this->Connect(wxEVT_KEY_DOWN, wxKeyEventHandler(MainFrameBaseClass::OnKeyDown), NULL, this);
    m_scrollWin->Connect(wxEVT_LEFT_DOWN, wxMouseEventHandler(MainFrameBaseClass::OnMouseLD), NULL, this);
    m_scrollWin->Connect(wxEVT_MOTION, wxMouseEventHandler(MainFrameBaseClass::OnMouseMotion), NULL, this);
    m_textCtrlOBJh->Connect(wxEVT_COMMAND_TEXT_UPDATED, wxCommandEventHandler(MainFrameBaseClass::OnTextctrlobjhTextUpdated), NULL, this);
    this->Connect(m_menuItem81->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileOpen), NULL, this);
    this->Connect(m_menuItem7->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Connect(m_menuItem9->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    this->Connect(m_menuItem103->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnNextSelection), NULL, this);
    this->Connect(m_menuItem107->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnClickClearAll), NULL, this);
    this->Connect(m_menuItemCam->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnMenuCamera), NULL, this);
    this->Connect(m_menuItemFile->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnMenuFileOpen), NULL, this);
    
}

MainFrameBaseClass::~MainFrameBaseClass()
{
    this->Disconnect(wxEVT_KEY_DOWN, wxKeyEventHandler(MainFrameBaseClass::OnKeyDown), NULL, this);
    m_scrollWin->Disconnect(wxEVT_LEFT_DOWN, wxMouseEventHandler(MainFrameBaseClass::OnMouseLD), NULL, this);
    m_scrollWin->Disconnect(wxEVT_MOTION, wxMouseEventHandler(MainFrameBaseClass::OnMouseMotion), NULL, this);
    m_textCtrlOBJh->Disconnect(wxEVT_COMMAND_TEXT_UPDATED, wxCommandEventHandler(MainFrameBaseClass::OnTextctrlobjhTextUpdated), NULL, this);
    this->Disconnect(m_menuItem81->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileOpen), NULL, this);
    this->Disconnect(m_menuItem7->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Disconnect(m_menuItem9->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    this->Disconnect(m_menuItem103->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnNextSelection), NULL, this);
    this->Disconnect(m_menuItem107->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnClickClearAll), NULL, this);
    this->Disconnect(m_menuItemCam->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnMenuCamera), NULL, this);
    this->Disconnect(m_menuItemFile->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnMenuFileOpen), NULL, this);
    
}
